import {test} from 'node:test';
import assert from 'node:assert/strict';
import worker,{validateJourney} from '../worker/index.js';
const value={entrance:'highway',region:'west',selected:'santasi',destination:'santasi',itinerary:['fengyangyi']};
function env(){const rows=new Map();return {rows,TRUSTED_IDENTITY_GATEWAY:'sites',DB:{prepare(sql){return {bind(...args){return {async first(){return rows.get(args[0])??null;},async run(){assert.ok(sql.includes('ON CONFLICT(user_id)'));rows.set(args[0],{payload:args[1],updated_at:args[2]});return {success:true};}};}};}},ASSETS:{fetch:()=>new Response('asset')}};}
const req=(method,user,body=value,origin='https://site.example')=>new Request(origin+'/api/journey',{method,headers:{...(user?{'oai-authenticated-user-id':user}:{}),...(method==='PUT'?{'content-type':'application/json',origin}:{})},...(method==='PUT'?{body:JSON.stringify(body)}:{})});
test('authenticated journeys survive subsequent reads and remain isolated by account',async()=>{const e=env();assert.equal((await worker.fetch(req('PUT','user-A'),e)).status,200);assert.deepEqual((await (await worker.fetch(req('GET','user-A'),e)).json()).journey,value);assert.equal((await (await worker.fetch(req('GET','user-B'),e)).json()).journey,null);assert.equal(e.rows.size,1);});
test('anonymous requests cannot read or write a journey',async()=>{const e=env();for(const method of ['GET','PUT'])assert.equal((await worker.fetch(req(method,null),e)).status,401);assert.equal(e.rows.size,0);});
test('invalid, oversized and foreign-origin writes never change stored rows',async()=>{const e=env();assert.equal((await worker.fetch(req('PUT','a',{...value,destination:'bogus'}),e)).status,400);const cross=new Request('https://site.example/api/journey',{method:'PUT',headers:{'oai-authenticated-user-id':'a','content-type':'application/json',origin:'https://foreign.example'},body:JSON.stringify(value)});assert.equal((await worker.fetch(cross,e)).status,403);assert.equal((await worker.fetch(req('PUT','a',{...value,extra:'x'.repeat(9000)}),e)).status,413);assert.equal(e.rows.size,0);});
test('storage validation accepts the new scenic places and strips extraneous fields',()=>{const x=validateJourney({...value,itinerary:['zhoucheng','haishe','wase','jizhaoan','cangshan','wase'],userId:'other'});assert.equal(x.userId,undefined);assert.equal(x.itinerary.length,5);assert.throws(()=>validateJourney({...value,itinerary:['invalid']}));});
test('static requests retain asset handling and storage outages return a recoverable error',async()=>{assert.equal(await (await worker.fetch(new Request('https://site.example/index.html'),env())).text(),'asset');assert.equal((await worker.fetch(req('GET','a'),{})).status,503);assert.equal((await worker.fetch(req('DELETE','a'),env())).status,405);});
