/* Distributed licensed photographs and original-source remote references. See asset-sources.json. */
window.DALI_GALLERIES = {
  "fengyangyi": [
    {
      "src": "https://img-cdn.yndaily.com/catchimages/20250806/1754466316464045325.jpg?x-image-process=image/quality,q_95/strip",
      "thumb": "https://img-cdn.yndaily.com/catchimages/20250806/1754466316464045325.jpg?x-image-process=image/quality,q_95/strip",
      "caption": "凤阳邑村内改造庭院的花木、石铺地面与休息座椅。",
      "author": "云南日报·云新闻／大理市融媒体中心（未逐图署名）",
      "license": "源站未注明开放许可；版权所有，未经许可不得转载",
      "licenseUrl": null,
      "source": "https://www.yndaily.com/html/2025/yunxinwen_0806/137022.html",
      "width": 1400,
      "height": 1050,
      "position": "center",
      "remote": true,
      "redistributed": false
    },
    {
      "src": "https://img-cdn.yndaily.com/catchimages/20250806/1754466319815074270.jpg?x-image-process=image/quality,q_95/strip",
      "thumb": "https://img-cdn.yndaily.com/catchimages/20250806/1754466319815074270.jpg?x-image-process=image/quality,q_95/strip",
      "caption": "凤阳邑村内音乐空间入口的木牌、花木与旧院落墙面。",
      "author": "云南日报·云新闻／大理市融媒体中心（未逐图署名）",
      "license": "源站未注明开放许可；版权所有，未经许可不得转载",
      "licenseUrl": null,
      "source": "https://www.yndaily.com/html/2025/yunxinwen_0806/137022.html",
      "width": 1400,
      "height": 1050,
      "position": "center",
      "remote": true,
      "redistributed": false
    }
  ],
  "ancient-town": [
    {
      "src": "assets/ancient-town-south-gate.webp",
      "thumb": "assets/ancient-town-south-gate-thumb.webp",
      "caption": "大理古城南门正面，城楼、城墙与入口花坛。",
      "author": "Pixabay 用户 4537668",
      "license": "CC0 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
      "source": "https://commons.wikimedia.org/wiki/File:大理古城南门-2064560.jpg",
      "width": 3200,
      "height": 2398,
      "position": "center",
      "period": "day",
      "thumbWidth": 960,
      "thumbHeight": 719
    },
    {
      "src": "assets/ancient-town-renmin-road.webp",
      "thumb": "assets/ancient-town-renmin-road-thumb.webp",
      "caption": "雨天的大理古城人民路，街巷与两侧店铺。",
      "author": "瑞丽江的河水",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
      "source": "https://commons.wikimedia.org/wiki/File:大理古城人民路01.jpg",
      "width": 3200,
      "height": 2406,
      "position": "center",
      "period": "day",
      "thumbWidth": 960,
      "thumbHeight": 722
    },
    {
      "src": "assets/ancient-town-night-street.webp",
      "thumb": "assets/ancient-town-night-street-thumb.webp",
      "caption": "大理古城入夜时的街巷，沿街灯光勾勒白族屋檐",
      "author": "Jian Qiu（页面说明署名）；Commons上传者Donut~commonswiki",
      "license": "Public domain",
      "licenseUrl": "https://commons.wikimedia.org/wiki/File:Dali_night.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Dali_night.jpg",
      "width": 2048,
      "height": 1536,
      "position": "center",
      "period": "night",
      "thumbWidth": 960,
      "thumbHeight": 720
    },
    {
      "src": "assets/ancient-town-wuhua-night.webp",
      "thumb": "assets/ancient-town-wuhua-night-thumb.webp",
      "caption": "夜色中的五华楼，金色檐灯与拱门下的行人",
      "author": "Kcx36",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:%E5%A4%A7%E7%90%86%E5%8F%A4%E5%9F%8E%E4%BA%94%E5%8D%8E%E6%A5%BC%E5%A4%9C%E6%99%AF.jpg",
      "width": 1200,
      "height": 1600,
      "position": "center",
      "period": "night",
      "thumbWidth": 720,
      "thumbHeight": 960
    },
    {
      "src": "assets/ancient-town.jpg",
      "thumb": "assets/ancient-town-thumb.webp",
      "caption": "青瓦白墙里的生活",
      "author": "瑞丽江的河水",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
      "source": "https://commons.wikimedia.org/wiki/File:大理古城_-_航拍_-_2024-10-13_01.jpg",
      "width": 1800,
      "height": 1013,
      "position": "center",
      "thumbWidth": 960,
      "thumbHeight": 540
    }
  ],
  "longkan": [
    {
      "src": "https://tr-osdcp.qunarzz.com/tr-osd-tr-space/img/975cf5e59a6a4299d52d8a098cd31547.jpg",
      "thumb": "https://tr-osdcp.qunarzz.com/tr-osd-tr-space/img/975cf5e59a6a4299d52d8a098cd31547.jpg",
      "source": "https://touch.travel.qunar.com/comment/19524811",
      "caption": "龙龛湖岸的水杉与倒影，洱海和远山相映",
      "author": "旅游狂魔夏夏夏",
      "width": 2048,
      "height": 1366,
      "license": "来源页未提供开放复用许可；版权归原作者",
      "licenseUrl": null,
      "position": "center",
      "remote": true,
      "redistributed": false
    },
    {
      "src": "https://tr-osdcp.qunarzz.com/tr-osd-tr-space/img/fc4fc96699b124a62a782ccea7981540.jpg",
      "thumb": "https://tr-osdcp.qunarzz.com/tr-osd-tr-space/img/fc4fc96699b124a62a782ccea7981540.jpg",
      "source": "https://touch.travel.qunar.com/comment/19524811",
      "caption": "龙龛古渡牌坊、石铺湖岸与洱海",
      "author": "旅游狂魔夏夏夏",
      "width": 2048,
      "height": 1366,
      "license": "来源页未提供开放复用许可；版权归原作者",
      "licenseUrl": null,
      "position": "center",
      "remote": true,
      "redistributed": false
    },
    {
      "src": "https://dimg04.c-ctrip.com/images/0104l12000992m5gy4477.jpg",
      "thumb": "https://dimg04.c-ctrip.com/images/0104l12000992m5gy4477.jpg",
      "caption": "龙龛码头的亭子与湖面上空的云",
      "author": "无违旅行／携程游记（未逐图署名）",
      "license": "源站未注明开放许可",
      "licenseUrl": null,
      "source": "https://you.ctrip.com/travels/erhai2020651/4049597.html",
      "width": 1228,
      "height": 921,
      "position": "center",
      "remote": true,
      "redistributed": false
    }
  ],
  "caicun": [
    {
      "src": "assets/caicun-02.webp",
      "thumb": "assets/caicun-02-thumb.webp",
      "caption": "在才村向对岸望去，黄昏云层与湖面",
      "author": "Liuxingy",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
      "source": "https://commons.wikimedia.org/wiki/File:大理才村的洱海_02.jpg",
      "width": 3200,
      "height": 2133,
      "position": "center",
      "period": "day",
      "thumbWidth": 960,
      "thumbHeight": 640
    },
    {
      "src": "assets/caicun-04.webp",
      "thumb": "assets/caicun-04-thumb.webp",
      "caption": "才村近岸，水草与湖边游人",
      "author": "Liuxingy",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
      "source": "https://commons.wikimedia.org/wiki/File:大理才村的洱海_04.jpg",
      "width": 3200,
      "height": 2133,
      "position": "center",
      "period": "day",
      "thumbWidth": 960,
      "thumbHeight": 640
    },
    {
      "src": "assets/caicun.jpg",
      "thumb": "assets/caicun-thumb.webp",
      "caption": "从村口走到湖边",
      "author": "Liuxingy",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
      "source": "https://commons.wikimedia.org/wiki/File:大理才村的洱海_01.jpg",
      "width": 1800,
      "height": 1200,
      "position": "center",
      "thumbWidth": 960,
      "thumbHeight": 640
    }
  ],
  "panxi": [
    {
      "src": "https://k.sinaimg.cn/n/news/1_ori/upload/6e865411/652/w2048h1804/20250517/0ea3-3b07ed0c3e79b6b3c4b109a8c54cfaf4.jpg/w5000hdp.jpg",
      "thumb": "https://k.sinaimg.cn/n/news/1_ori/upload/6e865411/652/w2048h1804/20250517/0ea3-3b07ed0c3e79b6b3c4b109a8c54cfaf4.jpg/w5000hdp.jpg",
      "caption": "磻溪湖岸 S 弯，反方向俯瞰完整弯曲道路",
      "author": "视觉中国／新浪新闻",
      "license": "源站未注明开放许可",
      "licenseUrl": null,
      "source": "https://slide.news.sina.com.cn/c/slide_1_2841_608289.html/d/2",
      "width": 2048,
      "height": 1804,
      "position": "center",
      "remote": true,
      "redistributed": false
    },
    {
      "src": "https://k.sinaimg.cn/n/news/1_ori/upload/6e865411/347/w2048h1499/20250517/113d-fba455c61f8453eea1a8e9f18d710ce8.jpg/w5000hdp.jpg",
      "thumb": "https://k.sinaimg.cn/n/news/1_ori/upload/6e865411/347/w2048h1499/20250517/113d-fba455c61f8453eea1a8e9f18d710ce8.jpg/w5000hdp.jpg",
      "caption": "磻溪村临湖 S 弯与白族民居，向村落方向俯瞰",
      "author": "视觉中国／新浪新闻",
      "license": "源站未注明开放许可",
      "licenseUrl": null,
      "source": "https://slide.news.sina.com.cn/c/slide_1_2841_608289.html/d/1",
      "width": 2048,
      "height": 1499,
      "position": "center",
      "remote": true,
      "redistributed": false
    },
    {
      "title": "File:磻溪珠联阁 03.jpg",
      "width": 3000,
      "height": 1688,
      "author": "Kcx36",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File%3A%E7%A3%BB%E6%BA%AA%E7%8F%A0%E8%81%94%E9%98%81%2003.jpg",
      "src": "assets/panxi-commons-4.webp",
      "thumb": "assets/panxi-commons-4-thumb.webp",
      "position": "center",
      "caption": "磻溪村沿路风景 · 珠联阁（非 S 弯机位）",
      "thumbWidth": 960,
      "thumbHeight": 540
    }
  ],
  "xizhou": [
    {
      "src": "assets/xizhou-square.webp",
      "thumb": "assets/xizhou-square-thumb.webp",
      "caption": "喜洲四方街题名坊与白族建筑",
      "author": "Mx. Granger",
      "license": "CC0 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
      "source": "https://commons.wikimedia.org/wiki/File:Xizhou_Old_Town.jpg",
      "width": 3200,
      "height": 1855,
      "position": "center",
      "period": "day",
      "thumbWidth": 960,
      "thumbHeight": 557
    },
    {
      "src": "assets/xizhou-bai-architecture.webp",
      "thumb": "assets/xizhou-bai-architecture-thumb.webp",
      "caption": "白族民居门前的石狮与民族服饰人物",
      "author": "Luca Casartelli",
      "license": "CC BY-SA 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
      "source": "https://commons.wikimedia.org/wiki/File:Xizhou_Town_(21200714911).jpg",
      "width": 2048,
      "height": 1280,
      "position": "center",
      "period": "day",
      "thumbWidth": 960,
      "thumbHeight": 600
    },
    {
      "src": "assets/xizhou.jpg",
      "thumb": "assets/xizhou-thumb.webp",
      "caption": "田野与古镇相邻",
      "author": "Chris DeLacy",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
      "source": "https://commons.wikimedia.org/wiki/File:Rice_fields_and_the_town_of_Xizhou.JPG",
      "width": 1800,
      "height": 1192,
      "position": "center",
      "thumbWidth": 960,
      "thumbHeight": 636
    },
    {
      "src": "assets/xizhou-corner.webp",
      "thumb": "assets/xizhou-corner-thumb.webp",
      "caption": "喜洲古镇转角楼，木质立面、彩色玻璃与瓦檐细节",
      "author": "Kcx36",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:%E5%96%9C%E6%B4%B2%E5%8F%A4%E9%95%87-%E8%BD%AC%E8%A7%92%E6%A5%BC_01.jpg",
      "position": "center",
      "period": "day",
      "width": 3200,
      "height": 1800,
      "thumbWidth": 960,
      "thumbHeight": 540
    }
  ],
  "wenbi": [
    {
      "src": "assets/wenbi-gate.webp",
      "thumb": "assets/wenbi-gate-thumb.webp",
      "caption": "村口牌坊与石壁上的文笔村红字，近景实拍。",
      "author": "Kcx36",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:%E4%BA%91%E5%8D%97%E7%9C%81%E5%A4%A7%E7%90%86%E6%B5%B7%E4%B8%9C%E9%95%87%E6%96%87%E7%AC%94%E6%9D%91.jpg",
      "width": 3200,
      "height": 1800,
      "position": "center",
      "period": "day",
      "thumbWidth": 960,
      "thumbHeight": 540
    },
    {
      "src": "https://img-cdn.yndaily.com/catchimages/20251126/1764152367475032978.jpg?x-image-process=image%2Fquality%2Cq_95%2Fstrip%2Fstrip",
      "thumb": "https://img-cdn.yndaily.com/catchimages/20251126/1764152367475032978.jpg?x-image-process=image%2Fquality%2Cq_95%2Fstrip%2Fstrip",
      "source": "https://www.yndaily.com/html/2025/yunxinwen_1128/139377.html",
      "caption": "文笔村临湖休闲空间，屋檐下的人们与窗外洱海",
      "author": "云南日报·云新闻记者 李丽",
      "width": 1400,
      "height": 933,
      "license": "来源页未提供开放复用许可；版权归原作者",
      "licenseUrl": null,
      "position": "center",
      "remote": true,
      "redistributed": false
    }
  ],
  "xiaoputuo": [
    {
      "src": "assets/xiaoputuo-island.webp",
      "thumb": "assets/xiaoputuo-island-thumb.webp",
      "caption": "从东岸眺望小普陀全岛、楼阁、湖面与苍山。",
      "author": "Kcx36",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:%E6%B4%B1%E6%B5%B7%E5%B0%8F%E6%99%AE%E9%99%80_02.jpg",
      "width": 3200,
      "height": 1440,
      "position": "center",
      "period": "day",
      "thumbWidth": 960,
      "thumbHeight": 432
    },
    {
      "src": "assets/xiaoputuo-boat.webp",
      "thumb": "assets/xiaoputuo-boat-thumb.webp",
      "caption": "从小普陀岛上向岸边拍摄拉绳渡船、游客与对岸村落。",
      "author": "Mx. Granger",
      "license": "CC0",
      "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "source": "https://commons.wikimedia.org/wiki/File:%E5%B0%8F%E6%99%AE%E9%99%80_2.jpg",
      "width": 3200,
      "height": 2400,
      "position": "center",
      "period": "day",
      "thumbWidth": 960,
      "thumbHeight": 720
    },
    {
      "src": "assets/xiaoputuo.jpg",
      "thumb": "assets/xiaoputuo-thumb.webp",
      "caption": "水中的小岛与楼阁",
      "author": "Mx. Granger",
      "license": "CC0",
      "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
      "source": "https://commons.wikimedia.org/wiki/File:小普陀_1.jpg",
      "width": 1600,
      "height": 1200,
      "position": "78% center",
      "thumbWidth": 960,
      "thumbHeight": 720
    }
  ],
  "shuanglang": [
    {
      "src": "assets/shuanglang-blue-lake.webp",
      "thumb": "assets/shuanglang-blue-lake-thumb.webp",
      "caption": "双廊湖畔眺望洱海，蓝色湖面、远山薄雾与飞鸟。",
      "author": "Mekal Zheng (@mekalz)",
      "license": "Unsplash License",
      "licenseUrl": "https://unsplash.com/license",
      "source": "https://unsplash.com/photos/a-body-of-water-surrounded-by-mountains-and-trees-aYelCQepJBs",
      "position": "center",
      "period": "day",
      "width": 3000,
      "height": 1688,
      "thumbWidth": 960,
      "thumbHeight": 540
    },
    {
      "src": "assets/shuanglang-south.webp",
      "thumb": "assets/shuanglang-south-thumb.webp",
      "caption": "从水上看双廊南部沿湖村落建筑和背后的山体。",
      "author": "Liuxingy",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:%E6%B4%B1%E6%B5%B7%E4%B8%8A%E6%9C%9B%E5%8F%8C%E5%BB%8A%E9%95%87%E5%8D%97%E9%83%A8_01.jpg",
      "width": 3200,
      "height": 2133,
      "position": "center",
      "period": "day",
      "thumbWidth": 960,
      "thumbHeight": 640
    },
    {
      "src": "assets/shuanglang-lakeside.webp",
      "thumb": "assets/shuanglang-lakeside-thumb.webp",
      "caption": "双廊湖畔白色高脚桌椅、洱海与远山。",
      "author": "Zhangmoon618",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "source": "https://commons.wikimedia.org/wiki/File:Shuanglang,_Dali,_Yunnan,_China_02.jpg",
      "width": 3200,
      "height": 2091,
      "position": "center",
      "period": "day",
      "thumbWidth": 960,
      "thumbHeight": 627
    },
    {
      "src": "assets/shuanglang.jpg",
      "thumb": "assets/shuanglang-thumb.webp",
      "caption": "把生活放在湖边",
      "author": "Zhangmoon618",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
      "source": "https://commons.wikimedia.org/wiki/File:Shuanglang,_Dali,_Yunnan,_China_01.jpg",
      "width": 1800,
      "height": 1013,
      "position": "center",
      "thumbWidth": 960,
      "thumbHeight": 540
    }
  ],
  "zhoucheng": [
    {
      "src": "https://www.xinhuanet.com/photo/20251122/60577af78eeb4681a387f395f0cbd934/2025112260577af78eeb4681a387f395f0cbd934_20251122de1113fa559745e1b606e422602ec98f.jpg",
      "thumb": "https://www.xinhuanet.com/photo/20251122/60577af78eeb4681a387f395f0cbd934/2025112260577af78eeb4681a387f395f0cbd934_20251122de1113fa559745e1b606e422602ec98f.jpg",
      "source": "https://www.xinhuanet.com/photo/20251122/60577af78eeb4681a387f395f0cbd934/c.html?page=2",
      "caption": "周城璞真染坊院落与晾晒的扎染布（2025年11月21日，无人机拍摄）",
      "author": "新华社记者 胡超",
      "width": 1004,
      "height": 565,
      "license": "来源页未提供开放复用许可；版权归原作者",
      "licenseUrl": null,
      "position": "center",
      "remote": true,
      "redistributed": false,
      "period": "day",
      "shotDate": "2025-11-21"
    },
    {
      "src": "https://www.xinhuanet.com/photo/20251122/60577af78eeb4681a387f395f0cbd934/2025112260577af78eeb4681a387f395f0cbd934_2025112212486f7dc35b469fa81b2ead57ff5b20.jpg",
      "thumb": "https://www.xinhuanet.com/photo/20251122/60577af78eeb4681a387f395f0cbd934/2025112260577af78eeb4681a387f395f0cbd934_2025112212486f7dc35b469fa81b2ead57ff5b20.jpg",
      "source": "https://www.xinhuanet.com/photo/20251122/60577af78eeb4681a387f395f0cbd934/c.html?page=3",
      "caption": "周城璞真染坊，手艺人晾晒扎染成品（2025年11月21日）",
      "author": "新华社记者 胡超",
      "width": 1019,
      "height": 679,
      "license": "来源页未提供开放复用许可；版权归原作者",
      "licenseUrl": null,
      "position": "center",
      "remote": true,
      "redistributed": false,
      "period": "day",
      "shotDate": "2025-11-21"
    },
    {
      "src": "https://www.xinhuanet.com/photo/20251122/60577af78eeb4681a387f395f0cbd934/2025112260577af78eeb4681a387f395f0cbd934_202511221e9072109202472d8269c23c4bbaadb6.jpg",
      "thumb": "https://www.xinhuanet.com/photo/20251122/60577af78eeb4681a387f395f0cbd934/2025112260577af78eeb4681a387f395f0cbd934_202511221e9072109202472d8269c23c4bbaadb6.jpg",
      "source": "https://www.xinhuanet.com/photo/20251122/60577af78eeb4681a387f395f0cbd934/c.html",
      "caption": "周城村璞真染坊，段银妹与段利兰在拆花（2025年11月21日）",
      "author": "新华社记者 胡超",
      "width": 1024,
      "height": 683,
      "license": "来源页未提供开放复用许可；版权归原作者",
      "licenseUrl": null,
      "position": "center",
      "remote": true,
      "redistributed": false,
      "period": "day",
      "shotDate": "2025-11-21"
    }
  ],
  "santasi": [
    {
      "src": "assets/santasi-sunrays.webp",
      "thumb": "assets/santasi-sunrays-thumb.webp",
      "caption": "崇圣寺三塔、园林与远处洱海，云隙光照亮苍山脚下",
      "author": "huweijie07170",
      "license": "CC0",
      "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "source": "https://commons.wikimedia.org/wiki/File:%E5%B4%87%E5%9C%A3%E5%AF%BA%E4%B8%89%E5%A1%94-2404059.jpg",
      "position": "center",
      "period": "day",
      "width": 3200,
      "height": 2126,
      "thumbWidth": 960,
      "thumbHeight": 638
    },
    {
      "src": "assets/santasi-reflection.webp",
      "thumb": "assets/santasi-reflection-thumb.webp",
      "caption": "三塔与倒影池，蓝天映入水面",
      "author": "G41rn8",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File:Dali_2007_171.jpg",
      "width": 2592,
      "height": 1944,
      "position": "center",
      "period": "day",
      "thumbWidth": 960,
      "thumbHeight": 720
    },
    {
      "src": "assets/santasi-pond.webp",
      "thumb": "assets/santasi-pond-thumb.webp",
      "caption": "树荫下的三塔与园林倒影池",
      "author": "Zhangzhugang",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "source": "https://commons.wikimedia.org/wiki/File:Dali_Chongsheng_Si_2008.09.10_11-30-34.jpg",
      "width": 3072,
      "height": 2304,
      "position": "center",
      "period": "day",
      "thumbWidth": 960,
      "thumbHeight": 720
    }
  ],
  "cangshan": [
    {
      "src": "assets/cangshan-qingbixi.webp",
      "thumb": "assets/cangshan-qingbixi-thumb.webp",
      "caption": "苍山清碧溪，峡谷中的瀑布与碧潭",
      "author": "JLDragon",
      "license": "Public domain",
      "licenseUrl": "https://commons.wikimedia.org/wiki/File:%E5%A4%A7%E7%90%86%E8%8B%8D%E5%B1%B1%E7%9A%84%E6%B8%85%E7%A2%A7%E6%BA%AA.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:%E5%A4%A7%E7%90%86%E8%8B%8D%E5%B1%B1%E7%9A%84%E6%B8%85%E7%A2%A7%E6%BA%AA.jpg",
      "width": 3200,
      "height": 2400,
      "position": "center",
      "period": "day",
      "thumbWidth": 960,
      "thumbHeight": 720
    },
    {
      "src": "assets/cangshan-gantong-gate.webp",
      "thumb": "assets/cangshan-gantong-gate-thumb.webp",
      "caption": "苍山感通游览区域：感通寺山门与松林",
      "author": "Kcx36",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
      "source": "https://commons.wikimedia.org/wiki/File:%E6%84%9F%E9%80%9A%E5%AF%BA%E5%B1%B1%E9%97%A8.jpg",
      "width": 3200,
      "height": 1800,
      "position": "center",
      "period": "day",
      "thumbWidth": 960,
      "thumbHeight": 540
    }
  ],
  "jizhaoan": [
    {
      "title": "File:寂照庵大雄宝殿.jpg",
      "width": 3000,
      "height": 1350,
      "author": "Kcx36",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File%3A%E5%AF%82%E7%85%A7%E5%BA%B5%E5%A4%A7%E9%9B%84%E5%AE%9D%E6%AE%BF.jpg",
      "src": "assets/jizhaoan-commons-1.webp",
      "thumb": "assets/jizhaoan-commons-1-thumb.webp",
      "position": "center",
      "caption": "寂照庵大雄宝殿与庭院",
      "thumbWidth": 960,
      "thumbHeight": 432
    },
    {
      "title": "File:寂照庵山门.jpg",
      "width": 1687,
      "height": 3000,
      "author": "Kcx36",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "source": "https://commons.wikimedia.org/wiki/File%3A%E5%AF%82%E7%85%A7%E5%BA%B5%E5%B1%B1%E9%97%A8.jpg",
      "src": "assets/jizhaoan-commons-2.webp",
      "thumb": "assets/jizhaoan-commons-2-thumb.webp",
      "position": "center",
      "caption": "寂照庵山门与苍山林荫",
      "thumbWidth": 540,
      "thumbHeight": 960
    }
  ],
  "wase": [
    {
      "src": "assets/wase-temple.webp",
      "thumb": "assets/wase-temple-thumb.webp",
      "caption": "挖色镇大成武庙正门，白族传统建筑实景（2024年8月）",
      "author": "Kcx36",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
      "source": "https://commons.wikimedia.org/wiki/File:大成武庙_2024-08-20_01.jpg",
      "width": 3200,
      "height": 2403,
      "position": "50% 50%",
      "period": "day",
      "thumbWidth": 960,
      "thumbHeight": 721
    },
    {
      "src": "assets/wase-tower.webp",
      "thumb": "assets/wase-tower-thumb.webp",
      "caption": "挖色镇海印村高兴文笔塔，田野中的古塔（2024年8月）",
      "author": "Kcx36",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
      "source": "https://commons.wikimedia.org/wiki/File:高兴文笔塔_2024-08-20.jpg",
      "width": 1811,
      "height": 2412,
      "position": "50% 35%",
      "period": "day",
      "thumbWidth": 721,
      "thumbHeight": 960
    }
  ],
  "haishe": [
    {
      "src": "assets/haishe-01.webp",
      "thumb": "assets/haishe-01-thumb.webp",
      "caption": "海舌湿地公园草坪与树林，远处苍山云层",
      "author": "Kcx36",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
      "source": "https://commons.wikimedia.org/wiki/File:海舌湿地公园_01.jpg",
      "width": 3200,
      "height": 1440,
      "position": "50% 50%",
      "period": "day",
      "thumbWidth": 960,
      "thumbHeight": 432
    },
    {
      "src": "assets/haishe-02.webp",
      "thumb": "assets/haishe-02-thumb.webp",
      "caption": "海舌湿地公园宽阔绿地与树阵，真实宽幅视角",
      "author": "Kcx36",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
      "source": "https://commons.wikimedia.org/wiki/File:海舌湿地公园_02.jpg",
      "width": 3200,
      "height": 1440,
      "position": "50% 50%",
      "period": "day",
      "thumbWidth": 960,
      "thumbHeight": 432
    }
  ]
};
window.DALI_OVERVIEW = {
  "name": "洱海全景",
  "image": "assets/erhai.jpg",
  "author": "Brücke-Osteuropa",
  "license": "Public domain",
  "licenseUrl": "https://commons.wikimedia.org/wiki/Commons:Public_domain",
  "source": "https://commons.wikimedia.org/wiki/File:Erhai_Lake_Dali_17.JPG"
};
